version: 2

sources:
  - name: sample_data
    description: This is default sample snowflake_sample_data database
    database: snowflake_sample_data  
    schema: TPCDS_SF100TCL  
    tables:
      - name: customer
        description: details about customer